#!/bin/bash
# Quick deployment setup script
# Run this to make deployment easier

echo "🚀 BrandedBy Deployment Setup"
echo "=============================="
echo ""
echo "📋 Checklist for Cloudflare Pages Deployment:"
echo ""
echo "1️⃣  Create Cloudflare Account"
echo "   → https://dash.cloudflare.com/sign-up"
echo ""
echo "2️⃣  Get API Token"
echo "   → https://dash.cloudflare.com/profile/api-tokens"
echo "   → Create Token → Edit Cloudflare Workers"
echo ""
echo "3️⃣  Get Account ID"
echo "   → https://dash.cloudflare.com/"
echo "   → Look in bottom right corner"
echo ""
echo "4️⃣  Add GitHub Secrets"
echo "   → https://github.com/ganbaroff/brandedby-ai-platform/settings/secrets/actions"
echo "   → Add CLOUDFLARE_API_TOKEN"
echo "   → Add CLOUDFLARE_ACCOUNT_ID"
echo ""
echo "5️⃣  Create Cloudflare Pages Project"
echo "   → https://dash.cloudflare.com/"
echo "   → Pages → Create Project → Connect Git"
echo "   → Framework: None"
echo "   → Build: npm run build"
echo "   → Output: dist/client"
echo ""
echo "✅ Your site will be live at: https://brandedby.pages.dev"
echo ""
echo "📖 Full instructions in: DEPLOY_INSTRUCTIONS_RU.md"
