/**
 * 🤖 AUTO-GENERATED BY AUTONOMOUS BOT
 * Global Package Selection Context Provider
 */

import logger from "@/shared/logger";
import { createContext, ReactNode, useCallback, useState } from "react";

interface Package {
  name: string;
  price: number;
  duration: string;
  features: string[];
  popular: boolean;
  color: string;
}

interface PackageContextType {
  selectedPackage: Package | null;
  isLoading: boolean;
  processingPackage: string | null;
  selectPackage: (pkg: Package) => void;
  resetSelection: () => void;
  isPackageSelected: (packageName: string) => boolean;
  isPackageProcessing: (packageName: string) => boolean;
  hasSelection: boolean;
}

export const PackageContext = createContext<PackageContextType | undefined>(undefined);

export type { PackageContextType };

interface PackageProviderProps {
  children: ReactNode;
}

export function PackageProvider({ children }: PackageProviderProps) {
  const [selectedPackage, setSelectedPackage] = useState<Package | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [processingPackage, setProcessingPackage] = useState<string | null>(null);

  const selectPackage = useCallback((pkg: Package) => {
    // Bot: Prevent duplicate selections
    if (processingPackage || (selectedPackage && selectedPackage.name === pkg.name)) {
      return;
    }

    setProcessingPackage(pkg.name);
    setIsLoading(true);

    // Bot: Comprehensive logging with package details
    logger.logUserAction('package_selection_initiated', {
      packageName: pkg.name,
      price: pkg.price,
      duration: pkg.duration,
      popular: pkg.popular,
      previousSelection: selectedPackage?.name || null,
      timestamp: new Date().toISOString(),
      sessionId: crypto.randomUUID(),
      userAgent: navigator.userAgent,
      screenSize: `${screen.width}x${screen.height}`,
      page: 'home',
      section: 'pricing'
    });

    // Bot: Realistic processing simulation with success/error handling
    const processingTime = 1000 + Math.random() * 1500; // 1-2.5 seconds
    
    setTimeout(() => {
      // Bot: Success rate 95% (simulate occasional failures)
      const success = Math.random() > 0.05;
      
      if (success) {
        setSelectedPackage(pkg);
        setIsLoading(false);
        setProcessingPackage(null);

        logger.info('Package selection completed successfully', {
          packageName: pkg.name,
          price: pkg.price,
          processingTime: `${processingTime}ms`,
          success: true
        });

        // Bot: Trigger analytics for popular package
        if (pkg.popular) {
          logger.logUserAction('popular_package_selected', {
            packageName: pkg.name,
            conversionLikelihood: 'high',
            recommendedUpsells: ['premium_features', 'bulk_discount']
          });
        }

      } else {
        // Bot: Handle rare failure cases
        setIsLoading(false);
        setProcessingPackage(null);
        
        logger.error('Package selection failed', {
          packageName: pkg.name,
          error: 'Processing timeout',
          retry: true
        });
      }
    }, processingTime);

  }, [selectedPackage, processingPackage]);

  const resetSelection = useCallback(() => {
    const previousPackage = selectedPackage;
    
    setSelectedPackage(null);
    setIsLoading(false);
    setProcessingPackage(null);

    logger.logUserAction('package_selection_reset', {
      previousPackage: previousPackage?.name || null,
      timestamp: new Date().toISOString(),
      reason: 'user_initiated'
    });
  }, [selectedPackage]);

  const isPackageSelected = useCallback((packageName: string) => {
    return selectedPackage?.name === packageName;
  }, [selectedPackage]);

  const isPackageProcessing = useCallback((packageName: string) => {
    return processingPackage === packageName && isLoading;
  }, [processingPackage, isLoading]);

  const contextValue: PackageContextType = {
    selectedPackage,
    isLoading,
    processingPackage,
    selectPackage,
    resetSelection,
    isPackageSelected,
    isPackageProcessing,
    hasSelection: !!selectedPackage
  };

  return (
    <PackageContext.Provider value={contextValue}>
      {children}
    </PackageContext.Provider>
  );
}

// Removed from here - moved to separate hook file for Fast Refresh compatibility