/**
 * 🤖 AUTO-GENERATED BY AUTONOMOUS BOT
 * Enhanced Interactive Package Button Component
 */

import { memo } from "react";
import { Check, ArrowRight, Zap, Loader2, CheckCircle } from "lucide-react";
// 🤖 BOT: Using simplified local state for fast implementation
import { useState, useCallback } from "react";

interface PackageButtonProps {
  packageData: {
    name: string;
    price: number;
    duration: string;
    features: string[];
    popular: boolean;
    color: string;
  };
}

const EnhancedPackageButton = memo(function EnhancedPackageButton({ packageData }: PackageButtonProps) {
  // 🤖 BOT: Simplified local state for immediate functionality
  const [isSelected, setIsSelected] = useState(false);
  const [isProcessing, setIsProcessing] = useState(false);

  const handleClick = useCallback(() => {
    if (isProcessing || isSelected) return;
    
    setIsProcessing(true);
    
    // 🤖 BOT: Realistic processing simulation
    setTimeout(() => {
      setIsSelected(true);
      setIsProcessing(false);
      
      // Log the selection
      console.log(`🤖 BOT: Package "${packageData.name}" selected for $${packageData.price}`);
    }, 1200 + Math.random() * 800);
  }, [isProcessing, isSelected, packageData.name, packageData.price]);

  // Bot: Dynamic button content based on state
  const getButtonContent = () => {
    if (isProcessing) {
      return (
        <>
          <Loader2 className="w-5 h-5 animate-spin" />
          <span>Processing...</span>
        </>
      );
    }
    
    if (isSelected) {
      return (
        <>
          <CheckCircle className="w-5 h-5" />
          <span>Selected</span>
        </>
      );
    }

    return (
      <>
        <Zap className="w-5 h-5" />
        <span>Get Started</span>
        <ArrowRight className="w-4 h-4 group-hover:translate-x-1 transition-transform" />
      </>
    );
  };

  // Bot: Dynamic button styles based on state and package type
  const getButtonStyles = () => {
    const baseStyles = "w-full py-3 sm:py-4 px-6 rounded-xl sm:rounded-2xl font-semibold transition-all duration-500 transform flex items-center justify-center space-x-2 group";
    
    if (isSelected) {
      return `${baseStyles} bg-green-500 text-white shadow-lg shadow-green-500/25 scale-105 cursor-default`;
    }
    
    if (isProcessing) {
      return `${baseStyles} bg-blue-500 text-white animate-pulse cursor-wait`;
    }
    
    if (packageData.popular) {
      return `${baseStyles} bg-gradient-to-r ${packageData.color} text-white hover:shadow-2xl hover:shadow-purple-500/30 hover:scale-105 active:scale-95 hover:-translate-y-1`;
    }
    
    return `${baseStyles} bg-gray-100 text-gray-900 hover:bg-gray-200 hover:shadow-lg hover:scale-105 active:scale-95 hover:-translate-y-1 border-2 border-transparent hover:border-gray-300`;
  };

  return (
    <div 
      className={`relative bg-white rounded-2xl sm:rounded-3xl p-6 sm:p-8 border-2 transition-all duration-500 transform ${
        isSelected 
          ? 'border-green-400 shadow-2xl shadow-green-500/20 scale-105' 
          : isProcessing
            ? 'border-blue-400 shadow-2xl shadow-blue-500/20 animate-pulse'
            : packageData.popular 
              ? 'border-purple-200 shadow-2xl shadow-purple-500/20 hover:shadow-purple-500/30' 
              : 'border-gray-200 hover:border-purple-300'
      } ${isProcessing ? '' : 'hover:scale-105'}`}
    >
      {/* Bot: Enhanced Popular Badge */}
      {packageData.popular && (
        <div className="absolute -top-4 left-1/2 transform -translate-x-1/2">
          <div className="bg-gradient-to-r from-blue-600 to-purple-600 text-white px-4 py-2 sm:px-6 sm:py-2 rounded-full text-xs sm:text-sm font-semibold shadow-lg animate-bounce">
            ⭐ Most Popular
          </div>
        </div>
      )}

      {/* Bot: Selection Indicator */}
      {isSelected && (
        <div className="absolute -top-3 -right-3">
          <div className="bg-green-500 text-white rounded-full p-2 shadow-lg animate-pulse">
            <Check className="w-4 h-4" />
          </div>
        </div>
      )}

      <div className="text-center space-y-4 sm:space-y-6">
        <div>
          <h3 className="text-xl sm:text-2xl font-bold text-gray-900">{packageData.name}</h3>
          <div className="mt-3 sm:mt-4">
            <span className="text-4xl sm:text-5xl font-bold text-gray-900">${packageData.price}</span>
            <span className="text-gray-600 ml-2 text-sm sm:text-base">per video</span>
          </div>
          <p className="text-gray-600 mt-2 text-sm sm:text-base">{packageData.duration} video</p>
        </div>

        {/* Bot: Enhanced Features List */}
        <ul className="space-y-2 sm:space-y-3 text-left">
          {packageData.features.map((feature, index) => (
            <li 
              key={feature} 
              className="flex items-center space-x-3 group"
              style={{ 
                animationDelay: `${index * 100}ms`,
                animation: isSelected ? 'fadeInUp 0.5s ease-out forwards' : undefined
              }}
            >
              <Check className={`w-4 h-4 sm:w-5 sm:h-5 flex-shrink-0 transition-colors duration-300 ${
                isSelected ? 'text-green-500' : 'text-green-500'
              }`} />
              <span className={`text-sm sm:text-base transition-colors duration-300 ${
                isSelected ? 'text-green-800 font-medium' : 'text-gray-700'
              }`}>
                {feature}
              </span>
            </li>
          ))}
        </ul>

        {/* Bot: Enhanced Interactive Button */}
        <button 
          onClick={handleClick}
          disabled={isProcessing || isSelected}
          className={getButtonStyles()}
          aria-label={`Select ${packageData.name} package for $${packageData.price}`}
        >
          {getButtonContent()}
        </button>

        {/* Bot: Processing Indicator */}
        {isProcessing && (
          <div className="text-center">
            <div className="inline-flex items-center space-x-2 text-blue-600 text-sm animate-pulse">
              <div className="w-2 h-2 bg-blue-600 rounded-full animate-bounce" style={{ animationDelay: '0ms' }}></div>
              <div className="w-2 h-2 bg-blue-600 rounded-full animate-bounce" style={{ animationDelay: '150ms' }}></div>
              <div className="w-2 h-2 bg-blue-600 rounded-full animate-bounce" style={{ animationDelay: '300ms' }}></div>
              <span>Preparing your package...</span>
            </div>
          </div>
        )}

        {/* Bot: Success Message */}
        {isSelected && (
          <div className="text-center animate-fadeIn">
            <div className="inline-flex items-center space-x-2 text-green-600 text-sm font-medium bg-green-50 px-3 py-2 rounded-lg">
              <CheckCircle className="w-4 h-4" />
              <span>Package selected! Ready to proceed</span>
            </div>
          </div>
        )}
      </div>
    </div>
  );
});

export default EnhancedPackageButton;