/**
 * 🤖 AUTO-GENERATED BY AUTONOMOUS BOT
 * Enhanced Interactive Package Button Component
 */

import { trackingEvents } from "@/shared/tracking-integration";
import { ArrowRight, Loader2, Zap } from "lucide-react";
import { memo, useCallback, useState } from "react";
import { useNavigate } from "react-router";

interface PackageButtonProps {
  packageData: {
    name: string;
    price: number;
    duration: string;
    features: string[];
    popular: boolean;
    color: string;
  };
}

const EnhancedPackageButton = memo(function EnhancedPackageButton({ packageData }: PackageButtonProps) {
  const navigate = useNavigate();
  const [isProcessing, setIsProcessing] = useState(false);

  const handleClick = useCallback(() => {
    if (isProcessing) return;
    
    setIsProcessing(true);
    
    // Track package selection
    trackingEvents.packageSelected(packageData.name, packageData.price);
    
    // Navigate to payment with package data
    setTimeout(() => {
      navigate('/payment', { 
        state: { 
          packageType: packageData.name,
          amount: packageData.price,
          duration: packageData.duration,
          features: packageData.features
        } 
      });
      setIsProcessing(false);
    }, 300);
  }, [isProcessing, navigate, packageData]);

  // Button content and styles
  const getButtonContent = () => {
    if (isProcessing) {
      return (
        <>
          <Loader2 className="w-5 h-5 animate-spin" />
          <span>Loading...</span>
        </>
      );
    }

    return (
      <>
        <Zap className="w-5 h-5" />
        <span>Choose Package</span>
        <ArrowRight className="w-4 h-4 group-hover:translate-x-1 transition-transform" />
      </>
    );
  };

  const getButtonStyles = () => {
    const baseStyles = "w-full py-3 sm:py-4 px-6 rounded-xl sm:rounded-2xl font-semibold transition-all duration-300 transform flex items-center justify-center space-x-2 group";
    
    if (isProcessing) {
      return `${baseStyles} bg-blue-500 text-white cursor-wait`;
    }
    
    if (packageData.popular) {
      return `${baseStyles} bg-gradient-to-r ${packageData.color} text-white hover:shadow-2xl hover:shadow-purple-500/30 hover:scale-105 active:scale-95 hover:-translate-y-1`;
    }
    
    return `${baseStyles} bg-gray-100 text-gray-900 hover:bg-gray-200 hover:shadow-lg hover:scale-105 active:scale-95 hover:-translate-y-1 border-2 border-transparent hover:border-gray-300`;
  };

  return (
    <div className="space-y-4">
      {/* Interactive Button */}
      <button 
        onClick={handleClick}
        disabled={isProcessing}
        className={getButtonStyles()}
        aria-label={`Choose ${packageData.name} package for $${packageData.price}`}
      >
        {getButtonContent()}
      </button>

      {/* Processing Indicator */}
      {isProcessing && (
        <div className="text-center">
          <div className="inline-flex items-center space-x-2 text-blue-600 text-sm">
            <div className="w-2 h-2 bg-blue-600 rounded-full animate-bounce" style={{ animationDelay: '0ms' }}></div>
            <div className="w-2 h-2 bg-blue-600 rounded-full animate-bounce" style={{ animationDelay: '150ms' }}></div>
            <div className="w-2 h-2 bg-blue-600 rounded-full animate-bounce" style={{ animationDelay: '300ms' }}></div>
            <span>Redirecting to checkout...</span>
          </div>
        </div>
      )}
    </div>
  );
});

export default EnhancedPackageButton;