/**
 * 🤖 AUTO-GENERATED BY AUTONOMOUS BOT
 * Package Context Hook (Separated for Fast Refresh)
 */

import { useContext } from "react";
import { PackageContext, PackageContextType } from "@/react-app/contexts/PackageContext";

export function usePackageContext(): PackageContextType {
  const context = useContext(PackageContext);
  if (context === undefined) {
    throw new Error('usePackageContext must be used within a PackageProvider');
  }
  return context;
}