/**
 * 🤖 AUTO-GENERATED BY AUTONOMOUS BOT
 * Enhanced Package Selection Hook with Interactive States
 */

import { useState, useCallback } from "react";
import logger from "@/shared/logger";

interface PackageState {
  selectedPackage: string | null;
  isLoading: boolean;
  processingPackage: string | null;
  lastSelected: string | null;
}

export const usePackageSelection = () => {
  const [state, setState] = useState<PackageState>({
    selectedPackage: null,
    isLoading: false,
    processingPackage: null,
    lastSelected: null
  });

  const selectPackage = useCallback((packageName: string, price: number) => {
    // Bot: Add immediate visual feedback
    setState(prev => ({ 
      ...prev, 
      processingPackage: packageName,
      isLoading: true 
    }));

    // Bot: Log user interaction with comprehensive data
    logger.logUserAction('package_selected', {
      packageName,
      price,
      previousSelection: state.lastSelected,
      timestamp: new Date().toISOString(),
      sessionId: crypto.randomUUID(),
      page: 'home',
      section: 'pricing'
    });

    // Bot: Simulate processing with realistic delay
    setTimeout(() => {
      setState(prev => ({
        ...prev,
        selectedPackage: packageName,
        lastSelected: packageName,
        isLoading: false,
        processingPackage: null
      }));

      // Bot: Log successful selection
      logger.info(`Package "${packageName}" selected successfully`, {
        price,
        duration: '2.5s',
        success: true
      });

      // Bot: Trigger next action based on package
      if (packageName === 'Pro') {
        logger.info('Popular package selected - enhanced tracking enabled');
      }

    }, 1200 + Math.random() * 800); // Bot: Realistic processing time

  }, [state.lastSelected]);

  const resetSelection = useCallback(() => {
    setState({
      selectedPackage: null,
      isLoading: false,
      processingPackage: null,
      lastSelected: state.selectedPackage
    });
    
    logger.logUserAction('package_selection_reset', {
      previousPackage: state.selectedPackage,
      timestamp: new Date().toISOString()
    });
  }, [state.selectedPackage]);

  const isPackageSelected = useCallback((packageName: string) => {
    return state.selectedPackage === packageName;
  }, [state.selectedPackage]);

  const isPackageProcessing = useCallback((packageName: string) => {
    return state.processingPackage === packageName && state.isLoading;
  }, [state.processingPackage, state.isLoading]);

  return {
    selectedPackage: state.selectedPackage,
    isLoading: state.isLoading,
    selectPackage,
    resetSelection,
    isPackageSelected,
    isPackageProcessing,
    hasSelection: !!state.selectedPackage
  };
};